### ISSUE TITLE
False positives for invalid routes

### ISSUE THREAD

**Issue by ambasta** [delhivery/moirai#6]
**Describe the bug**
Some routes in the system are detected as invalid (non-existant source/target), even though the sources/targets are valid and active in the system.

**To Reproduce**

**Expected behavior**

**Comment by AshwaniDelhivery** [comment]
Started to look into this issue.

**Comment by AshwaniDelhivery** [comment]
We are using 2 API.

1) To get all the nodes of the graph ( we are using FAAS API and making all nodes with **Active** status as nodes of the graph.
API: https://faas-dev-api.delhivery.com/v3/facilities/

2) After making all the nodes of the graph. we are getting all the scheduled routes from another API:
API: https://thanos-bk-staging.delhivery.com/v1/scheduledroutes

Issue is there are 2 kind of facilities code we are getting from scheduled Routes API:

1) Facilities which does not exist in the FAAS DEV API like: INPBAAFW
2) Facilities which are InActive in the FAAS DEV API: INMHAALJ,IND400072AAB, IN501218A1A.

To fix this issue, we should be taking the data from Prod API of both. Which would be sync we the real state of the data.

**Comment by AshwaniDelhivery** [comment]
All the facilities that we are getting as false ( Are already inactive or not found in prod FAAS API).

    facility_id_list = "ND400102AAB,IN800008A1A,IND110095AAB,IND110095AAB,INHRAAJY,INKAAAWZ,INKAAAWZ,INHRAAJW,IN122022A1A,IN122022A1A,INHRAAJY,IN110041A1A,IN110041A1A,INHRAAJY,IN711409A1B,INAPAAOU,INAPAAOU,INAPAAOU,INAPAAOU,INAPAAOU,INWBAAOX,INHRAAJW,BDDKAAAZ,BDDKAAAZ,INRJAAMC,INRJAAMC,INRJAAMC,INRJAAMC,INRJAAMC,INBRALRK,INBRALRK,INBRALRK,INBRALRK,INTSAALI,INTSALIU,INTSAALI,INTSALIU,INTSAALI,INTSALIU,INTSAALI,INTSAALI,INTSALIU,INTSAAOF,INTSAAOF,INTSAAOF,INTSAAOF,INTSAAOF,IN711409A1B,IND303002AAA,INRJAARB,IND303002AAA,INRJAARB,IND303002AAA,IND303002AAA,INRJAARB,INKAAAUC,INKAAATQ,INKAAAUC,INKAAATQ,INKAAAUC,INKAAAUC,INKAAAUC,INKAAATQ,INKAAATQ,INMHALLV,INMHALLV,INMHALLV,INMHALLV,INAPAAOG,INAPAAOG,INAPAAOG,INAPAAOG,INAPAAOG,INTSAAOQ,INTSAAOQ,INTSAAOQ,INTSAAOQ,INTSAAOQ,INTSAAOQ,INTSAAOQ,IND244301AAA,IND244301AAA,IND244301AAA,IND244301AAA,IND244301AAA,IND577116AAA,IND577116AAA,IND577116AAA,IND577116AAA,IND577116AAA,INAPAAOE,INAPAAOE,INAPAAOE,INAPAAOE,INAPAAOE,IND343029AAB,IND343029AAB,IND343029AAB,IND343029AAB,IND343029AAB,IN507301A1A,IN507301A1A,IN507301A1A,IN507301A1A,IN507301A1A,INKAAAWC,INKAAAWC,INKAAAWC,INKAAAWC,INKAAAWC,INAPAAOS,INAPAAOS,INAPAAOS,INAPAAOS,INKAAAWF,INKAAAWF,INKAAAWF,INKAAAWF,INKAAAWF,INTSAALR,IND503185AAA,INTSAALR,INTSAALR,INTSAALR,INTSAALR,IND503185AAA,IND503185AAA,IND503185AAA,INAPAAPN,INAPAAPN,INAPAAPN,INAPAAPN,INAPAAPN,INKLAAIA,INKLAAIA,INKLAAIA,INKLAAIA,INKLAAIA,IND332404AAA,IND332404AAA,IND332404AAA,INTNAAMS,INTNAAMS,INTNAAMS,INTNAAMS,INTNAAMS,INTNAAMS,IND110095AAB,INHRAAJW,INTSAALQ,INTSAALQ,INTSAALQ,INTSAALQ,INAPAAOV,INAPAAOV,INAPAAOV,INAPAAOV,IN110041A1A,BDBGAAAG,BDBGAAAG,BDBGAAAG,BDBGAAAG,BDBGAAAG,BDBGAAAG,BDDKAAAO,BDDKAAAP,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDDKAAAP,BDDKAAAP,BDDKAAAP,BDDKAAAP,BDDKAAAP,BDDKAAAP,IND231208AAA,IND231208AAA,IND231208AAA,IND231208AAA,INTNAANW,INTNAANW,INTNAANW,INTNAANW,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDDKAAAO,BDBGAAAG,BDBGAAAG,BDBGAAAG,BDBGAAAG,BDBGAAAG,BDBGAAAG,INKAAAWA,INKAAAWA,INKAAAWA,INKAAAWA,INKAAAWA,INMHABFH,INMHABFH,INMHABFH,INMHABFH,INASAAHY,INASAAHY,INASAAHY,INASAAHY,IND110030AAC,IND110030AAC,IND110030AAC,IND110030AAC,IND110030AAC,IND110030AAC,IND627005AAA,IN122022A1A,IN122022A1A,INHRAAJY,INHRAAIS,BDKHAAAH,BDKHAAAH,IN110041A1A,IN110041A1A,INHRAAJY,IND627005AAA,IND627005AAA,INMHABFH,INMHABFH,INMHABFH,INMHABFH,IND110030AAC,IND110030AAC,IND110030AAC,IND110030AAC,IND110030AAC,IND110030AAC,INDLAAGG,INDLAAGG,INDLAAGG,INDLAAGG,BDDKAAAZ,IND000000AFS,IND000000AFS,IND000000AFS,IND627005AAA,INKAAAVZ,INKAAAVZ,INKAAAVZ,INKAAAVZ,INKAAAVZ,IND627005AAA,IND124507A1E,IND332713AAA,IND332713AAA,IND332713AAA,IND332713AAA,IND332713AAA,IND382430AAC,IND627005AAA,INMPALIX,INMPALIX,INMPALIX,INMPALIX,INMPALIX,INTSAALJ,INTSAALJ,INTSAALJ,INTSAALJ,INTSAALJ,IND627005AAA,BDRPALVM,BDRPALVM,IND627005AAA,IND110095AAB,IN110077A1B,IN110077A1B,IN110077A1B,IN711409A1B,IND500010AAB,INWBAAOX"

**Comment by AshwaniDelhivery** [comment]
we can use the below code snippet to test if facilities are inactive or not from FAAS prod API:

def get_active_facilities(facility_id_list):
    facility_id_list = "ND400102AAB,IN800008A1A"
    header = {
        "Authorization": "Bearer XXXXXXXXXXXXXXXXXXXXXXXXXX",
        "x-user-app-id": "ExpectedPath",
        "Content-Type": "application/json",
    }
    url = "https://faas-api.delhivery.com/v3/facilities/?status=active&facility_code={}" 
    response = requests.request("GET", url.format(facility_id_list), headers=header).json()
    if len(response.get("result").get("data")) >= 1:
        print("Few entries are present in FAAS as Active, please re verify all the codes again")

**Comment by rishabhraj08** [comment]
For the above mentioned list of facility codes queried the data over ES and all the facilities mentioned status is not active
ES Query
GET facility/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "terms": {
            "facility_code": [
              "IND400102AAB",
              "IN800008A1A",
              "IND110095AAB",
              "IND110095AAB",
              "INHRAAJY",
              "INKAAAWZ",
              "INKAAAWZ",
              "INHRAAJW",
              "IN122022A1A",
              "IN122022A1A",
              "INHRAAJY",
              "IN110041A1A",
              "IN110041A1A",
              "INHRAAJY",
              "IN711409A1B",
              "INAPAAOU",
              "INAPAAOU",
              "INAPAAOU",
              "INAPAAOU",
              "INAPAAOU",
              "INWBAAOX",
              "INHRAAJW",
              "BDDKAAAZ",
              "BDDKAAAZ",
              "INRJAAMC",
              "INRJAAMC",
              "INRJAAMC",
              "INRJAAMC",
              "INRJAAMC",
              "INBRALRK",
              "INBRALRK",
              "INBRALRK",
              "INBRALRK",
              "INTSAALI",
              "INTSALIU",
              "INTSAALI",
              "INTSALIU",
              "INTSAALI",
              "INTSALIU",
              "INTSAALI",
              "INTSAALI",
              "INTSALIU",
              "INTSAAOF",
              "INTSAAOF",
              "INTSAAOF",
              "INTSAAOF",
              "INTSAAOF",
              "IN711409A1B",
              "IND303002AAA",
              "INRJAARB",
              "IND303002AAA",
              "INRJAARB",
              "IND303002AAA",
              "IND303002AAA",
              "INRJAARB",
              "INKAAAUC",
              "INKAAATQ",
              "INKAAAUC",
              "INKAAATQ",
              "INKAAAUC",
              "INKAAAUC",
              "INKAAAUC",
              "INKAAATQ",
              "INKAAATQ",
              "INMHALLV",
              "INMHALLV",
              "INMHALLV",
              "INMHALLV",
              "INAPAAOG",
              "INAPAAOG",
              "INAPAAOG",
              "INAPAAOG",
              "INAPAAOG",
              "INTSAAOQ",
              "INTSAAOQ",
              "INTSAAOQ",
              "INTSAAOQ",
              "INTSAAOQ",
              "INTSAAOQ",
              "INTSAAOQ",
              "IND244301AAA",
              "IND244301AAA",
              "IND244301AAA",
              "IND244301AAA",
              "IND244301AAA",
              "IND577116AAA",
              "IND577116AAA",
              "IND577116AAA",
              "IND577116AAA",
              "IND577116AAA",
              "INAPAAOE",
              "INAPAAOE",
              "INAPAAOE",
              "INAPAAOE",
              "INAPAAOE",
              "IND343029AAB",
              "IND343029AAB",
              "IND343029AAB",
              "IND343029AAB",
              "IND343029AAB",
              "IN507301A1A",
              "IN507301A1A",
              "IN507301A1A",
              "IN507301A1A",
              "IN507301A1A",
              "INKAAAWC",
              "INKAAAWC",
              "INKAAAWC",
              "INKAAAWC",
              "INKAAAWC",
              "INAPAAOS",
              "INAPAAOS",
              "INAPAAOS",
              "INAPAAOS",
              "INKAAAWF",
              "INKAAAWF",
              "INKAAAWF",
              "INKAAAWF",
              "INKAAAWF",
              "INTSAALR",
              "IND503185AAA",
              "INTSAALR",
              "INTSAALR",
              "INTSAALR",
              "INTSAALR",
              "IND503185AAA",
              "IND503185AAA",
              "IND503185AAA",
              "INAPAAPN",
              "INAPAAPN",
              "INAPAAPN",
              "INAPAAPN",
              "INAPAAPN",
              "INKLAAIA",
              "INKLAAIA",
              "INKLAAIA",
              "INKLAAIA",
              "INKLAAIA",
              "IND332404AAA",
              "IND332404AAA",
              "IND332404AAA",
              "INTNAAMS",
              "INTNAAMS",
              "INTNAAMS",
              "INTNAAMS",
              "INTNAAMS",
              "INTNAAMS",
              "IND110095AAB",
              "INHRAAJW",
              "INTSAALQ",
              "INTSAALQ",
              "INTSAALQ",
              "INTSAALQ",
              "INAPAAOV",
              "INAPAAOV",
              "INAPAAOV",
              "INAPAAOV",
              "IN110041A1A",
              "BDBGAAAG",
              "BDBGAAAG",
              "BDBGAAAG",
              "BDBGAAAG",
              "BDBGAAAG",
              "BDBGAAAG",
              "BDDKAAAO",
              "BDDKAAAP",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAP",
              "BDDKAAAP",
              "BDDKAAAP",
              "BDDKAAAP",
              "BDDKAAAP",
              "BDDKAAAP",
              "IND231208AAA",
              "IND231208AAA",
              "IND231208AAA",
              "IND231208AAA",
              "INTNAANW",
              "INTNAANW",
              "INTNAANW",
              "INTNAANW",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDDKAAAO",
              "BDBGAAAG",
              "BDBGAAAG",
              "BDBGAAAG",
              "BDBGAAAG",
              "BDBGAAAG",
              "BDBGAAAG",
              "INKAAAWA",
              "INKAAAWA",
              "INKAAAWA",
              "INKAAAWA",
              "INKAAAWA",
              "INMHABFH",
              "INMHABFH",
              "INMHABFH",
              "INMHABFH",
              "INASAAHY",
              "INASAAHY",
              "INASAAHY",
              "INASAAHY",
              "IND110030AAC",
              "IND110030AAC",
              "IND110030AAC",
              "IND110030AAC",
              "IND110030AAC",
              "IND110030AAC",
              "IND627005AAA",
              "IN122022A1A",
              "IN122022A1A",
              "INHRAAJY",
              "INHRAAIS",
              "BDKHAAAH",
              "BDKHAAAH",
              "IN110041A1A",
              "IN110041A1A",
              "INHRAAJY",
              "IND627005AAA",
              "IND627005AAA",
              "INMHABFH",
              "INMHABFH",
              "INMHABFH",
              "INMHABFH",
              "IND110030AAC",
              "IND110030AAC",
              "IND110030AAC",
              "IND110030AAC",
              "IND110030AAC",
              "IND110030AAC",
              "INDLAAGG",
              "INDLAAGG",
              "INDLAAGG",
              "INDLAAGG",
              "BDDKAAAZ",
              "IND000000AFS",
              "IND000000AFS",
              "IND000000AFS",
              "IND627005AAA",
              "INKAAAVZ",
              "INKAAAVZ",
              "INKAAAVZ",
              "INKAAAVZ",
              "INKAAAVZ",
              "IND627005AAA",
              "IND124507A1E",
              "IND332713AAA",
              "IND332713AAA",
              "IND332713AAA",
              "IND332713AAA",
              "IND332713AAA",
              "IND382430AAC",
              "IND627005AAA",
              "INMPALIX",
              "INMPALIX",
              "INMPALIX",
              "INMPALIX",
              "INMPALIX",
              "INTSAALJ",
              "INTSAALJ",
              "INTSAALJ",
              "INTSAALJ",
              "INTSAALJ",
              "IND627005AAA",
              "BDRPALVM",
              "BDRPALVM",
              "IND627005AAA",
              "IND110095AAB",
              "IN110077A1B",
              "IN110077A1B",
              "IN110077A1B",
              "IN711409A1B",
              "IND500010AAB",
              "INWBAAOX"
            ]
          }
        },
        {
          "match": {
            "status": "active"
          }
        }
      ]
    }
  }
}

**Comment by ambasta** [comment]
@AshwaniDelhivery Thanks for confirming
